apiVersion: v1
kind: Service
metadata:
  name: gpu-test-service
spec:
  selector:
    app: gpu-test
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: NodePort # or LoadBalancer if on a cloud provider
