apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: tr
spec:
  taskSpec:
    steps:
      - name: curl
        image: curlimages/curl
        command: ["curl"]
        args: ["-I", "registry-service.default.svc.cluster.local:5000/v2/_catalog"]
